### ISSUE TITLE
Server address and port fields ignored/hard-coded

### ISSUE THREAD

**Issue by matqua** [GeoSCADA/TransferHistory#1]
On line 102 and 290 of MainWindow.xaml.cs, the server address and port are hard-coded:

`ServerNode node = new ClearScada.Client.ServerNode("127.0.0.1", 5481);`

I was banging my head against the wall trying to determine why it would not connect to a remote server. Thank you for uploading the code.

After that, it was relatively painless to export about 7k worth of points with a total of about 50 million records. 

Thanks for the utility @SteveBeadle.

Matthew Quarisa
I2R Group

**Comment by SteveBeadle** [comment]
Resolved thank you.
